//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDiagnostico.PruebasUnitarias
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosticos
    {
        public Diagnosticos()
        {
            this.DetallesDiagnostico = new HashSet<DetallesDiagnostico>();
        }
    
        public int Id { get; set; }
        public int Empleado_Id { get; set; }
        public int Paciente_Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Enfermedad { get; set; }
    
        public virtual ICollection<DetallesDiagnostico> DetallesDiagnostico { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
